// c/shared_structs.h - PURE BRUTALIST NETCODE (UMBRELLA)
// AUTO-GENERATED BY build/net_codegen.lua
#pragma once
#include "net_01_constants.h"
#include "net_02_wire.h"
#include "net_03_memory.h"
#include "net_04_state.h"
#include "net_05_api.h"
