import os
import sys
from collections import defaultdict

def generate_manifest(root_dir):
    """
    Walks the repository and returns a dictionary of valid files grouped by
    their top-level directory.
    """
    ignore_dirs = {".venv", "bin", "logs", ".git", "__pycache__", ".vscode", ".idea"}
    valid_exts = {".c", ".h", ".lua", ".glsl", ".vert", ".frag", ".py", ".md", ".txt", ".bat", ".sh"}

    # Dictionary to hold lists of files, grouped by top-level directory
    manifest_groups = defaultdict(list)

    for root, dirs, files in os.walk(root_dir):
        # Modify dirs in-place to prevent os.walk from entering ignored directories
        dirs[:] = [d for d in dirs if d not in ignore_dirs]

        for file in files:
            # Check if file has a valid extension OR is exactly "LICENSE"
            if any(file.endswith(ext) for ext in valid_exts) or file == "LICENSE":
                # Get relative path and ensure forward slashes
                filepath = os.path.relpath(os.path.join(root, file), root_dir)
                filepath = filepath.replace(os.sep, "/")

                # Determine the top-level directory for grouping
                parts = filepath.split("/")
                group = parts[0] if len(parts) > 1 else "Root"

                manifest_groups[group].append(filepath)

    return manifest_groups

def print_manifest(groups):
    """
    Prints the grouped files in perfect Python syntax for copy-pasting.
    """
    print("INGESTION_MANIFEST = [")

    for group_name in sorted(groups.keys()):
        # Format the comment nicely (e.g., "host" -> "# Host")
        display_name = group_name.capitalize() if group_name != "Root" else "Root Files"
        print(f"    # {display_name}")

        # Print each file in alphabetical order within the group
        for filepath in sorted(groups[group_name]):
            print(f'    "{filepath}",')

        print("")  # Blank line between groups for visual breathing room

    print("]")

def write_manifest(groups, output_file="ingestion_manifest.py"):
    """
    Writes the grouped files in perfect Python syntax directly to a file,
    completely omitting any files that match the blacklist.
    """
    omitted_count = 0
    added_count = 0

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# ingestion_manifest.py\n")
        f.write("# (Auto-generated by generate_manifest.py)\n\n")
        f.write("INGESTION_MANIFEST = [\n")

        for group_name in sorted(groups.keys()):
            # Filter files against the blacklist first
            valid_files = []
            for filepath in sorted(groups[group_name]):
                filename = os.path.basename(filepath)
                # Check if either the full path or just the filename is blacklisted
                if filepath in BLACKLIST or filename in BLACKLIST:
                    omitted_count += 1
                    continue
                valid_files.append(filepath)

            # If the whole group got blacklisted/empty, skip printing the header
            if not valid_files:
                continue

            # Format the comment nicely (e.g., "host" -> "# Host")
            display_name = group_name.capitalize() if group_name != "Root" else "Root Files"
            f.write(f"    # {display_name}\n")

            # Write each valid file
            for filepath in valid_files:
                f.write(f'    "{filepath}",\n')
                added_count += 1

            f.write("\n")  # Blank line between groups for visual breathing room

        f.write("]\n")

    print(f" [OK] Manifest generated: {added_count} files mapped, {omitted_count} omitted via blacklist.")
    print(f" [OK] Saved directly to -> {output_file}")

if __name__ == "__main__":
    # If executed from inside the /python folder, default to the parent directory.
    # Otherwise, default to the current working directory.
    default_dir = ".." if os.path.basename(os.getcwd()) == "python" else "."

    # Allow overriding the target directory via command line argument
    target_dir = sys.argv[1] if len(sys.argv) > 1 else default_dir

    # Generate the dictionary of files
    groups = generate_manifest(target_dir)
    print_manifest(groups)
    # Write directly to the python module
    write_manifest(groups, output_file="ingestion_manifest.py")
