import os
import sys
from collections import defaultdict

# --- Configuration ---
BLACKLIST = {

    "LICENSE",
    "README.md",
    "launch.bat",
    "launch.lua",
    "launch.sh",

    "docs/deps_c.md",
    "docs/deps_glsl.md",
    "docs/deps_lua.md",
    "docs/repo_ascii.txt",
    "docs/repo_tree.md",

    "network/protocol/dkjson.lua",

    "runtime/services/gpu/vulkan_headers.lua",
    "scripts/parse.py",

    "python/ascii_tree_cols.py",
    "python/ask.py",
    "python/ask_local.py",
    "python/generate_manifest.py",
    "python/ingest_codebase.py",
    "python/ingest_config.py",
    "python/ingest_embeddings.py",
    "python/ingest_topology.py",
    "python/ingest_validators.py",
    "python/rag_chat.py",
    "python/rag_config.py",
    "python/rag_embeddings.py",
    "python/rag_qdrant.py",
    "python/requirements.txt",
    "python/trace_deps_c.py",
    "python/trace_deps_glsl.py",
    "python/trace_deps_lua.py",
    "python/trace_tree.py",
}

def generate_manifest(root_dir):
    """
    Walks the repository and returns a dictionary of valid files grouped by
    their top-level directory.
    """
    ignore_dirs = {".venv", "bin", "logs", ".git", "__pycache__", ".vscode", ".idea"}
    valid_exts = {".c", ".h", ".lua", ".glsl", ".vert", ".frag", ".py", ".md", ".txt", ".bat", ".sh"}

    manifest_groups = defaultdict(list)

    for root, dirs, files in os.walk(root_dir):
        # Modify dirs in-place to prevent os.walk from entering ignored directories
        dirs[:] = [d for d in dirs if d not in ignore_dirs]

        for file in files:
            if any(file.endswith(ext) for ext in valid_exts) or file == "LICENSE":
                filepath = os.path.relpath(os.path.join(root, file), root_dir)
                filepath = filepath.replace(os.sep, "/")

                parts = filepath.split("/")
                group = parts[0] if len(parts) > 1 else "Root"

                manifest_groups[group].append(filepath)

    return manifest_groups

def build_manifest_string(groups):
    """
    Applies the blacklist and builds the final Python code string.
    Returns the string and the statistics.
    """
    lines = [
        "# ingestion_manifest.py",
        "# (Auto-generated by generate_manifest.py)",
        "",
        "INGESTION_MANIFEST = ["
    ]

    omitted_count = 0
    added_count = 0

    for group_name in sorted(groups.keys()):
        valid_files = []
        for filepath in sorted(groups[group_name]):
            filename = os.path.basename(filepath)

            if filepath in BLACKLIST or filename in BLACKLIST:
                omitted_count += 1
                continue
            valid_files.append(filepath)

        if not valid_files:
            continue

        display_name = group_name.capitalize() if group_name != "Root" else "Root Files"
        lines.append(f"    # {display_name}")

        for filepath in valid_files:
            lines.append(f'    "{filepath}",')
            added_count += 1

        lines.append("")  # Visual breathing room

    lines.append("]")

    return "\n".join(lines), added_count, omitted_count

def process_manifest(groups, output_file="ingestion_manifest.py"):
    """
    Generates the manifest text, prints it, and writes it to disk.
    """
    content, added, omitted = build_manifest_string(groups)

    # 1. Print to terminal (replaces old print_manifest)
    print(content)
    print()

    # 2. Write directly to Python file (replaces old write_manifest)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(content + "\n")

    print(f" [OK] Manifest generated: {added} files mapped, {omitted} omitted via blacklist.")
    print(f" [OK] Saved directly to -> {output_file}")

if __name__ == "__main__":
    # If executed from inside the /python folder, default to the parent directory.
    # Otherwise, default to the current working directory.
    default_dir = ".." if os.path.basename(os.getcwd()) == "python" else "."

    target_dir = sys.argv[1] if len(sys.argv) > 1 else default_dir

    groups = generate_manifest(target_dir)
    process_manifest(groups, output_file="python/ingestion_manifest.py")
